#!/usr/bin/env bash
#pings an ip address 5 times

if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

#extract the ip address from the argument
ip_address=$1

#ping the specified address 5 times
ping -c 5 "$ip_address"
