#!/usr/bin/env bash
#displays "To infinity and beyond" indefinitely, witha
#    sleep of 2 after each iteration of the loop
#Display "I am invincible!!!" between each iteration
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
