#!/usr/bin/env bash
#displays "Best School" 10 times using while loop

minute=1

while [ $minute -le 59 ]; do
	echo "$minute"
	
	hour=0
	while [ $hour -le 12 ]; do
		if [ $minute -eq 59 ]; then
			echo "Hour: $hour"
		fi
		((hour++))
	done
	((minute++))
done
