#!/usr/bin/env bash
#changes the ip address of localhost and facebook.com

#check if the script is run with root previledges
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root. Please use sudo"
	exit 1
fi

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

#Display the updated hosts file
cp -f ~/hosts.new /etc/hosts
