#!/usr/bin/env bash
#changes the ip address of localhost and facebook.com

#check if the script is run with root previledges
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root. Please use sudo"
	exit 1
fi

#update /etc/hosts file
echo "127.0.0.2	localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

#Display the updated hosts file
cat /etc/hosts
